[project]
name = "canmatrix_webapp"
version = "25.0.0"
description = "streamlit webapp for canmatrix python package"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10, <=3.14"
authors = [{ name = "chaitu-ycr", email = "chaitu.ycr@gmail.com" }]
keywords = ["python", "canmatrix", "streamlit", "webapp"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows"
]
dependencies = [
    "canmatrix[arxml,fibex,kcd,xls,xlsx]",
    "streamlit",
]

[project.urls]
homepage = "https://github.com/chaitu-ycr/automotive-test-kit/tree/main/packages/canmatrix_webapp"
repository = "https://github.com/chaitu-ycr/automotive-test-kit"
documentation = "https://chaitu-ycr.github.io/automotive-test-kit/packages/canmatrix_webapp"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
