[project]
name = "kmtronic_usb_relay"
version = "25.0.0"
description = "Python library for KMTronic USB Relay"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10, <=3.14"
authors = [{ name = "chaitu-ycr", email = "chaitu.ycr@gmail.com" }]
keywords = ["python", "KMTronic", "USB", "relay", "app"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows"
]
dependencies = [
    "pyserial",
    "customtkinter",
    "fastapi[all]",
]

[project.urls]
homepage = "https://github.com/chaitu-ycr/kmtronic_usb_relay"
repository = "https://github.com/chaitu-ycr/kmtronic_usb_relay"
documentation = "https://chaitu-ycr.github.io/kmtronic_usb_relay/"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
