[project]
name = "can_log_analyzer"
version = "25.0.0"
description = "CAN log Analyzer"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10, <=3.14"
authors = [{ name = "chaitu-ycr", email = "chaitu.ycr@gmail.com" }]
keywords = ["python", "CAN", "log", "analyzer"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows"
]
dependencies = [
    "cantools",
    "python-can",
    "pandas",
    "plotly",
    "streamlit",
]

[project.urls]
homepage = "https://github.com/chaitu-ycr/automotive-test-kit"
repository = "https://github.com/chaitu-ycr/automotive-test-kit"
documentation = "https://chaitu-ycr.github.io/automotive-test-kit/packages/can_log_analyzer"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
